name: carebellmom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  group_button: ^5.3.4
  flutter_image_slideshow: ^0.1.6
  curved_navigation_bar: ^1.0.6
  animated_notch_bottom_bar: ^1.0.3
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  flutter_fast_forms: ^18.1.0
  dropdown_search: ^6.0.2
  shared_preferences: ^2.5.3
  sliver_tools: ^0.2.12
  giffy_dialog: ^2.3.0 
  material_dialogs: ^1.1.5
  lottie: ^3.3.1
  custom_radio_grouped_button: ^2.2.1
  slide_action: ^0.0.2
  im_stepper: ^1.0.1+1
  flutter_cache_manager: ^3.4.1
  bottom_picker: ^3.0.0
  flutter_holo_date_picker: ^2.0.0
  matertino_radio: ^1.0.5
  flutter_expandable_fab: ^2.4.1
  carousel_slider: ^5.1.1
  popup_menu_plus: ^0.0.6
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  google_generative_ai : ^0.2.2
  page_transition : ^2.2.1
  fl_chart: ^0.65.0
  provider: ^6.0.5
  flutter_onboarding_slider: ^1.0.11

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/login_page/
    - assets/intro_page/
    - assets/index_page/
    - assets/jk/
    - assets/personal_page/
    - assets/chatbot/


  fonts:
    
    - family : Inter
      fonts:
        
        - asset: assets/fonts/Inter/static/Inter_28pt-Light.ttf
          weight: 200
