name: flutter_project
description: A Flutter project for managing patients, nurses, and admin functionalities.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_image_slideshow: ^0.1.0
  animated_notch_bottom_bar: ^0.1.0
  flutter_speed_dial: ^3.0.0
  font_awesome_flutter: ^9.0.0
  flutter_fast_forms: ^0.1.0
  dropdown_search: ^2.0.0
  sliver_tools: ^0.1.0
  material_dialogs: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/intro_page/
    - assets/login_page/
    - assets/personal_page/
    - assets/jk/